-- MySQL Script generated by MySQL Workbench
-- Fri Nov 17 16:23:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ecomerce_projeto_full_stack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ecomerce_projeto_full_stack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecomerce_projeto_full_stack` DEFAULT CHARACTER SET utf8 ;
USE `Ecomerce_projeto_full_stack` ;

-- -----------------------------------------------------
-- Table `Ecomerce_projeto_full_stack`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecomerce_projeto_full_stack`.`produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecomerce_projeto_full_stack`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecomerce_projeto_full_stack`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `quantidade` SMALLINT NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `fk_pedidos_produtos_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_produtos`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `Ecomerce_projeto_full_stack`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
